### ISSUE TITLE
Texture bits are interpreted as signed byte rather than unsigned byte.

### ISSUE THREAD

**Issue by hanslovsky** [scenerygraphics/scenery#102]
I am using a texture from a buffer that I generate from image data. The buffer is a `ByteBuffer` wrapped around a `byte[]` array. Intuitively, I would expect 8 bits of that buffer to interpreted as `unsigned byte` but it is interpreted as `byte` instead, e.g. `0xff` is interpreted as `-1` instead of `255`. As a result, the highest value, any channel can have is `127`, as negative numbers are treated like zero (black). This is an excerpt of how I add the texture to the material:
```java
final Material m = new Material();
m.getTransferTextures().put( "texture", new GenericTexture( "texture", dimensions, numChannels, GLTypeEnum.Byte, ByteBuffer.wrap( texture ), true, true ) );
m.getTextures().put( "diffuse", "fromBuffer:texture" );
box.setMaterial( m );
```
I created a working example at:
https://gist.github.com/hanslovsky/6dcad29151387970422217236ad56a15#file-simplesceneryexamplegradienttexturejavafx-java
Note, that each side of the box should be a gradient from black to white, but instead, half of each side of the box is black.

If you replace
```java
texture[ i + 0 ] = ( byte ) r;
texture[ i + 1 ] = ( byte ) g;
texture[ i + 2 ] = ( byte ) b;
texture[ i + 3 ] = ( byte ) a;
```
by
```java
texture[ i + 0 ] = ( byte ) Math.min( r, 127 );
texture[ i + 1 ] = ( byte ) Math.min( g, 127 );
texture[ i + 2 ] = ( byte ) Math.min( b, 127 );
texture[ i + 3 ] = ( byte ) Math.min( a, 127 );
```
you can see that the texture covers each side of the box completely, but is flat with a gray value of 127 in the upper half.

**Comment by hanslovsky** [comment]
@skalarproduktraum I was thinking about looking into the issue myself but I would like to avoid duplicate effort. Have you been working on it already? If not, I'll take it on.
What editor/ide do you recommend for kotlin and do you have a style guide/formatter file?

**Comment by skalarproduktraum** [comment]
@hanslovsky No I have not (yet :-D) -- and I'd be very happy to accept a PR from you :

**Comment by hanslovsky** [comment]
I will try intellij. Eclipse seems to have issues with mixed kotlin/java code (even though I installed the kotlin plugin).

**Comment by skalarproduktraum** [comment]
Hey @hanslovsky,

I have just realized the mistake, which is merely just counterintuitive and not really a bug:
The default type for GenericTexture is `GLTypeEnum.Byte`, while to achieve the behaviour you want, you need `GLTypeEnum.UnsignedByte`. 

I have changed the default in cc20074 to `GLTypeEnum.UnsignedByte`, which is I guess more practical. I'll close this for now, let me know if you disagree or if I got something wrong.

cheers!

**Comment by hanslovsky** [comment]
Sorry for the late reply. This makes a lot of sene, being in Java for too long I forgot there are unsigned types.

**Comment by skalarproduktraum** [comment]
No prob. That exact issue keeps biting me again and again :D
