### ISSUE TITLE
Renderers should be switchable on-line

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/scenery#106]
The parameters for swapping between vulkan and opengl aren't documented anywhere that is obvious.

**Comment by skalarproduktraum** [comment]
Run the scenery-based application with the VM flag `-Dscenery.Renderer=VulkanRenderer`.  

In 0.1.x, the Vulkan renderer was still pretty experimental, but it has matured now -- so this will be documented better and made more obvious for 0.2.0. Another option would be to make this a scenery Setting, so Renderer.createRenderer would use that instead of the system property. Opinions?

**Comment by kephale** [comment]
Having it be a scenery Setting is preferable, but is hot toggling renderers actually viable? I would be wary about making something a Setting if it is fixed after launching, but that might be a silly position to take...

**Comment by skalarproduktraum** [comment]
I was thinking about having read-only settings as well. Switching the renderer on-the-fly is not easily possible at the moment, but also not entirely impossible.

**Comment by skalarproduktraum** [comment]
When I actually think about it, it might not be such a bad idea to have the renderer online-switchable. For the Vulkan renderer e.g., there are additional instance and device extensions required, if you want to use it with an HMD, at least for OpenVR. These extensions enable additional semaphores for signalling, and memory sharing with external application (for example, to submit a Vulkan texture to be rendered in the headset). Now on-the-fly switching to an HMD would require tearing down the whole Vulkan renderer, and reconstructing it, as a Vulkan instance is a pretty basic element. If the user now decides to switch to the HMD, it would not be nice to force a restart of the application.

**Comment by kephale** [comment]
I support a hot swappable renderer.

**Comment by skalarproduktraum** [comment]
I renamed the issue to something that is more appropriate for where the discussion has evolved to. Original issue fixed and closed at #109.
