### ISSUE TITLE
Out of the box error for VRControllerExample on Arch+Vive+dual 1080

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/scenery#118]
This message is what I'm getting out of the box:

```
[main] INFO VRControllerExample - Started application as PID 24435
Unable to read VR Path Registry from /home/kharrington/.config/openvr/openvrpaths.vrpath
[main] ERROR OpenVRHMD - Initialization error - Installation path could not be located (110)
[main] ERROR VRControllerExample - This demo is intended to show the use of OpenVR controllers, but no OpenVR-compatible HMD could be initialized.
````

**Comment by skalarproduktraum** [comment]
Hey Kyle, 

the error you are seeing is not related to scenery, but to your Steam/SteamVR installation. Do you have the latest drivers, and latest Steam version installed? Please also try switching to the Steam beta versions. Also make sure to follow the SteamVR for Linux README at https://github.com/ValveSoftware/SteamVR-for-Linux -- maybe it's also a better place to file this issue there if it still persists after following the instructions?

**Comment by kephale** [comment]
Mmm... this is the error that came from the multi GPU setup. Closing... 
(Future people are directed to look into scenery.VulkanRenderer.Device VM flag: https://github.com/scenerygraphics/scenery/blob/master/src/main/kotlin/graphics/scenery/backends/vulkan/README.md)

**Comment by skalarproduktraum** [comment]
Ah, so this was for the OpenGL renderer? As far as I can read the docs at SteamVR-Linux, OpenGL is not even supported there yet.
