### ISSUE TITLE
Embed SceneryPanel into Swing and/or JavaFX windows

### ISSUE THREAD

**Issue by ctrueden** [scenerygraphics/scenery#162]
Scenery always currently (to my knowledge) always creates its own native window right now, leaning on the backing paradigm (e.g. JOGL). We will need the ability to embed a scenery scene in an existing window, e.g. a `javax.swing.JFrame`. There are many advantages: the ability to attach a Swing menu bar, include 3D panes in tabbed panes along with other controls, etc. This will be useful for KNIME in particular.

**Comment by skalarproduktraum** [comment]
There are two options now for embedding scenery in an application:

* using the JavaFX interface directly, via SceneryPanel and embedding that one in a `Stage`
* using the JavaFX interface indirectly, by embedding the SceneryPanel in a JFXPanel (as it is done now in SciView)

I think these are enough embedding options for the moment, and should also work with KNIME. I'll close this for the moment. Please reopen if you differ!
