### ISSUE TITLE
Screenshot emits GL error 0x502

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/scenery#174]
The screenshot still happens, but this error is emitted:

```
Info: GLReadBufferUtil.readPixels: pre-exisiting GL error 0x502
```

**Comment by skalarproduktraum** [comment]
Please also run this one with `-Djogl.debug.DebugGL=1`.

**Comment by skalarproduktraum** [comment]
Could you give me some more detail about when this is happening? Is this happening with the standard scenery examples, or with SciView, or in conjunction with funimage?

**Comment by skalarproduktraum** [comment]
I was just able to reproduce this with JavaFXTexturedCubeExample. The latest commit (1a4f139) contains a tentative fix. In case this does not fix the problem, please reopen.
