### ISSUE TITLE
BoundingGrid does not listen to scale

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/scenery#184]
If fitInto was called on the Node, then you get a result like this:

Also generating the BoundingGrid takes a surprisingly long time (multiple seconds) and completely blocks the thread.

![screenshot from 2018-06-20 11-08-55](https://user-images.githubusercontent.com/400105/41652264-7942e9f4-747a-11e8-8eb9-026247cb0a88.png)

**Comment by skalarproduktraum** [comment]
I shall investigate. The amount of time taken results from the font generation, which only happens once though. They should be cached on-disk nevertheless...

**Comment by kephale** [comment]
I have a suspicion actually. I think its shader loading time.

**Comment by skalarproduktraum** [comment]
It's definitely the font rendering. It takes some time to generate the distance fields via OpenCL. I'll cache them to disk soon so they're not recalculated with each new start.

**Comment by skalarproduktraum** [comment]
Just tried to reproduce the issue with pure scenery and couldn't. The bounding grid adapts to scaling as well. Do you have the model file somewhere and could load it with ReadModelExample and see if the same odd behaviour occurs?

**Comment by kephale** [comment]
This happens with model: https://github.com/scenerygraphics/SciView/blob/master/src/main/resources/WieseRobert_simplified_Cip1.stl

To test in SciView, just add a BoundingGrid in:
https://github.com/scenerygraphics/SciView/blob/master/src/main/java/sc/iview/commands/demo/MeshDemo.java

**Comment by skalarproduktraum** [comment]
Thanks, will try to reproduce!
