### ISSUE TITLE
Volume rendering on OpenGL has odd artifact at distance

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/scenery#187]
![out-1](https://user-images.githubusercontent.com/400105/41846519-cdd86c80-786e-11e8-96a2-2b1d50fc5782.gif)

artifact is on left hand side of window. the voxels that change by a large amount when the camera is rotated

**Comment by skalarproduktraum** [comment]
Does this still occur after using normalized 3D textures?

**Comment by skalarproduktraum** [comment]
*poke*

**Comment by kephale** [comment]
That image was an 8-bit binary with true values = 255.

**Comment by skalarproduktraum** [comment]
This should not occur anymore, can you confirm, @kephale?

**Comment by kephale** [comment]
Looks good to me
