### ISSUE TITLE
X3D file I/O

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/scenery#19]
It would be nice to be able to read/write entire scenes with the X3D standard (or another standard if more convenient). @kmader might want this one too.

**Comment by skalarproduktraum** [comment]
I was thinking about maybe implementing COLLADA support (https://en.wikipedia.org/wiki/COLLADA), as this is also supported by _lots_ of 3D software packages. I'll dig a little deeper in the formats and see what would be best.

**Comment by kmader** [comment]
I added a primitive JSON scene format, but something else could be nice (https://github.com/4Quant/SceneryNeuralNetDemo/blob/master/src/test/scala/scenery.tests/TestTachyonSceneReader.scala#L54)

**Comment by skalarproduktraum** [comment]
This will be handled by imagej-mesh soon, so I'm closing this here.
