### ISSUE TITLE
Do not center Volume

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/scenery#206]
We want the isosurface of a volume to align with the correct image data from the Volume without any additional registration. Currently SciView is moving the volume to the corner to achieve this, but that causes some issues. The Volume's scale should be checked at the same time. SciView is also doing some scaling to achieve the registration effect: https://github.com/scenerygraphics/sciview/blob/04b6007b9314efe38c3320fd0ed7b37c7e351bb0/src/main/java/sc/iview/SciView.java#L1158

**Comment by skalarproduktraum** [comment]
This has been addressed in the PR #216 -- mind having a look there? 👍

**Comment by skalarproduktraum** [comment]
Closing this does mean "please merge the PR" or ...?

**Comment by kephale** [comment]
Yeah, I remember testing this out a while ago. We'll have to update the complementary hacks in `addVolume` of `SciView.java`
