### ISSUE TITLE
Screenshot should have an override that forces screenshot overwrite

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/scenery#215]
https://github.com/scenerygraphics/scenery/blob/69b76112d3697bdb6c551b007a3718a1957fbf47/src/main/kotlin/graphics/scenery/backends/Renderer.kt#L63

When a screenshot is recorded it is always "nice" and writes to a new filename if the requested filename is in use. Sometimes this is not desirable.

**Comment by skalarproduktraum** [comment]
But @kephale, I implemented this just for you ┻━┻ ︵ヽ(`Д´)ﾉ︵﻿ ┻━┻ 

I'll add a flag, of course :)

**Comment by skalarproduktraum** [comment]
Closed with 1e3c17fb0d99a69b24d9120fd1a2b6026dfed43f
