### ISSUE TITLE
AWT Canvas

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/scenery#23]
If SceneryDefaultApplication is used and the target application is trying to embed within a JPanel, then Scenery needs to hand off a newtCanvasAWT.

ClearVolume has snippets for it already:
- something like [this](https://github.com/ClearVolume/ClearVolume/blob/dec443a5fa5f8ee460ebb49ff5b4ef972a1dbfe1/src/java/clearvolume/renderer/cleargl/ClearGLVolumeRenderer.java#L360) is needed in SceneryDefaultApplication.main()

and i think a little more stuff is needed, but I'm still poking. I currently chopped main() up and made a separate function to begin the sleep thread at the end of main().

**Comment by kephale** [comment]
Or alternatively: 

`
thread {
            while (glWindow!!.isVisible) {
                Thread.sleep(10)
            }
            glWindow.stop()
        }`

**Comment by skalarproduktraum** [comment]
With #79, there is now JavaFX support. I don't think supporting AWT additionally of that is very futureproof. Opinions, @kephale?

**Comment by kephale** [comment]
The concern is embedding in KNIME, where I believe Swing panels are the standard for wrapping UI elements.

**Comment by skalarproduktraum** [comment]
JavaFX can be embedded in Swing: https://docs.oracle.com/javase/8/javafx/interoperability-tutorial/swing-fx-interoperability.htm

**Comment by skalarproduktraum** [comment]
Closing this for the moment -- in case issues with Swing embedding should pop up, we'll track this in a separate issue.
