### ISSUE TITLE
Line shader has color/material error

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/scenery#233]
Note that in this screenshot there is a single red line, but it has black segments for some reason.

![image](https://user-images.githubusercontent.com/400105/53995309-aa097f80-4102-11e9-807b-647882d2b54b.png)

**Comment by kephale** [comment]
![ezgif-4-b44411ef2717](https://user-images.githubusercontent.com/400105/54831001-ef47b880-4c8f-11e9-860f-74ab2abc7ec4.gif)

**Comment by skalarproduktraum** [comment]
@kephale I think this should be fixed. Yes/no?

**Comment by kephale** [comment]
Closing this as completed
