### ISSUE TITLE
BDV texture binding issue?

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/scenery#235]
In SciView, linking to scenery `0.7.0-beta-2-SNAPSHOT`

```
[SciJava-4b6ea751-Thread-1] WARN SceneryContext - No binding found for tpietzsch.cache.TextureCache@7fb8bad0
[SciJava-4b6ea751-Thread-1] WARN SceneryContext - No binding found for tpietzsch.example2.LookupTextureARGB@277566ff
[SciJava-4b6ea751-Thread-1] ERROR SceneryContext - Binding for tpietzsch.example2.LookupTextureARGB@277566ff not found, despite trying deferred binding. (binding=BindingState(binding=1, uniformName=null, reallocate=false)/sampler=null)
```

**Comment by skalarproduktraum** [comment]
The warning can be there, the error should not. I shall have a look. Is this in any way dataset-dependent?

**Comment by kephale** [comment]
I have no reason to expect it to be dataset dependent, it was a 7gb 8 bit 1
channel tiff

**Comment by skalarproduktraum** [comment]
I just experienced the same issue with a dataset. However, the dataset was actually there, just very dim and in a weird position. Can you try setting `Renderer.HDR.Exposure` to something like `20.0`? (e.g. by `sciView.getActiveSciView().getSettings().set("Renderer.HDR.Exposure", 20.0f)`) and see if you can find the dataset?

**Comment by kephale** [comment]
Still doesnt work

**Comment by kephale** [comment]
Ok, the BDVVolume does show up now, but on the SciView side it doesnt show up in the inspector. I wonder if this is related to the Error during object creation?

**Comment by skalarproduktraum** [comment]
The error should not prevent it showing up in the inspector actually, as it's just a message. Will investigate further...
