### ISSUE TITLE
Bug in OpenGL volume rendering

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/scenery#241]
When using the OpenGLRenderer on my ubuntu machine on the SciView volume render example I get a weird Y-dimension stretch 
![SciView - 2019-04-25 16 50 06](https://user-images.githubusercontent.com/400105/56767732-7bab3680-677a-11e9-99df-5e5c68b08f93.png)

**Comment by skalarproduktraum** [comment]
Are you still seeing this? I could not reproduce this issue.

**Comment by skalarproduktraum** [comment]
*poke*

**Comment by kephale** [comment]
Actually I'm getting 
```
Inconsistency detected by ld.so: dl-lookup.c: 111: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!
```
now
