### ISSUE TITLE
Change default keybindings for up/down

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/scenery#242]
The current choice of `space` and `shift space` makes it impossible to have consistent key modifiers for fast/slow modifier keys w.r.t. the WASD keys.

**Comment by skalarproduktraum** [comment]
What key combinations would you suggest?

**Comment by kephale** [comment]
In the past I've used WASD + Z C which doesn't conflict with any of the current default keybinds I believe.

I'm not picky as long as none of the directions use an extra modifier.

**Comment by skalarproduktraum** [comment]
In true vim spirit, I've changed up to K and down to J with 3765a42f 👍

**Comment by kephale** [comment]
Lol, I'm going to change them to Z and C in SciVIew then. K and J requires
2 hands.
