### ISSUE TITLE
Transparent background for fonts

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/scenery#263]
https://gitter.im/scenerygraphics/SciView?at=5d9c9005045925467216052e

![Screenshot from 2019-10-08 09-20-50](https://user-images.githubusercontent.com/400105/66400246-1dcc7d00-e9af-11e9-98fd-dd303284720e.png)

**Comment by skalarproduktraum** [comment]
Fixed in 80ca5d1 👍
