### ISSUE TITLE
Issues w.r.t. BVV integration

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/scenery#295]
Volume centering: 
The current behavior is non-intuitive, it uses the min() of the volume, but then introduces an offset as well. I would argue that the proper way to do this with the current setup is to ignore the min/max and center the volume. In the long run the proper way to do this is that HasGeometry should be an `Interval` with a min/max, and these should imply the coordinates instead of having different Nodes treated differently.

Volume scaling:
There might be an issue with volume scaling. Unsure of the specifics, but it looks like there might be a double scaling happening when using `.setScale()` on the volume

**Comment by skalarproduktraum** [comment]
I moved this into #292, to have that stuff in one place, let's continue the discussion there 👍
