### ISSUE TITLE
Material Colors are Vector3f instead of Vector4f

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/scenery#304]

**Comment by skalarproduktraum** [comment]
This is actually intended: Transparency is managed separately via Material.Blending, so the color ought to be Vector3f. Any objections against that? Otherwise I would close this as `wontfix`.

**Comment by kephale** [comment]
It is unfortunate to handle the transparency dimension independently. RGBA data is common, and loading it with:

```
n = Node()
dataPoint = floatArrayOf(1f, 1f, 1f, 1f)
imglib2Val = ARGBType( ARGBType.rgba( dataPoint[0], dataPoint[1], dataPoint[2], dataPoint[3] ) )
n.material.diffuse = Vector4f( dataPoint )
```

is better than

```
n = Node()
dataPoint = floatArrayOf(1f, 1f, 1f, 1f)
imglib2Val = ARGBType( ARGBType.rgba( dataPoint[0], dataPoint[1], dataPoint[2], dataPoint[3] ) )
n.material.diffuse = Vector3f( dataPoint[0], dataPoint[1], dataPoint[2] )
n.material.blending.transparency = dataPoint[3]
```

I wouldn't complain much if it is too much work to handle this since RGBA is a degenerate case for generalized N-D algorithms anyway. However, treating transparency independently does make it more degenerate.

**Comment by kephale** [comment]
Closing this one, we can reopen if it comes up again.
