### ISSUE TITLE
Node.updateWorld() does not propagate `force` flag in recursive mode

### ISSUE THREAD

**Issue by xulman** [scenerygraphics/scenery#313]
Hi,

if I'm in rush and do in user-land code the following on a `node` that is `wantsComposeModel == false`
```
node.updateWorld(true,true) //recursive and force
```
without setting the `needsUpdate` or `needsWorldUpdate` (because why?, when I have set the `force` flag.. right?), the [recursive path becomes effectively a no-operation](https://github.com/scenerygraphics/scenery/blob/c4f06028c374b188d283e431a181108b848188f9/src/main/kotlin/graphics/scenery/Node.kt#L277-L280) as the [`needsWorldUpdate` does not get set to true]( https://github.com/scenerygraphics/scenery/blob/c4f06028c374b188d283e431a181108b848188f9/src/main/kotlin/graphics/scenery/Node.kt#L263) temporarily

I would propose to change
```
        if ((needsUpdate or force) && wantsComposeModel) {
            this.composeModel()
```
to
```
        if (needsUpdate or force) {
            if (wantsComposeModel) this.composeModel()
```

Vlado

**Comment by xulman** [comment]
well, under the circumstances outlined above, the recursive part only not propagate the `force` flag to the children nodes.... so it is a no-operation for the children only if they have also not setup their `needsUpdate` or `needsUpdateWorld` flags beforehand

**Comment by skalarproduktraum** [comment]
I agree to your change! Changed in latest master.
