### ISSUE TITLE
0.7.0-beta-4 through 0.7.beta-7 specify wrong scm tag

### ISSUE THREAD

**Issue by ctrueden** [scenerygraphics/scenery#314]
See:
* https://github.com/scenerygraphics/scenery/blob/scenery-0.7.0-beta-4/pom.xml#L81
* https://github.com/scenerygraphics/scenery/blob/scenery-0.7.0-beta-5/pom.xml#L81
* https://github.com/scenerygraphics/scenery/blob/scenery-0.7.0-beta-6/pom.xml#L81
* https://github.com/scenerygraphics/scenery/blob/scenery-0.7.0-beta-7/pom.xml#L81

Because of this, the melting-pot clones scenery at 0.7.0-beta-3 instead of the correct tag. I added a check to notice that this is happening, and error out, but it's important to correct for any future releases, so that scenery can be tested properly in melting pot validation.

I'm not sure why this is happening, though... @skalarproduktraum, did you set this manually somehow? Would it be possible for you to use `release-version.sh` in future so that this is set correctly next time?

**Comment by skalarproduktraum** [comment]
I'd be happy to use release-version.sh, but I have to admit that in the past it has confused me too much. Is there a way to perform a rollback of the changes it made in case something goes wrong?

**Comment by skalarproduktraum** [comment]
( @ctrueden )

**Comment by ctrueden** [comment]
> Is there a way to perform a rollback of the changes it made in case something goes wrong?

Before running it, push any pending commits upstream, and check that your working copy is clean (although the script also checks this). Then, if something goes wrong, you can reset back to the pushed state using:
```
git reset --hard 'HEAD@{u}'
```

If the release fails building artifacts (main code, javadocs, etc.), no harm done.

If the release fails during deployment, it's more annoying to deal with, but that's true regardless of whether `release-version.sh` or some other release mechanism is used. No matter what, you've got some artifacts but not others deployed to the remote Maven repository. In the case of `release-version.sh` there is also a pushed tag on GitHub. So assuming you address whatever caused the failing deployment, your subsequent options are then:

1. Release at the next higher patch version, burning the previous release as failed; or
2. Delete the incomplete release from the remote repository, and delete the remote and local tag, before rereleasing.

Hope that makes sense. Let me know if anything needs clarification.

**Comment by skalarproduktraum** [comment]
Thank you @ctrueden! I shall henceforth use `release-version.sh`, the missing piece for me was how to go back to the pushed state. Thanks for filling that gap in my knowledge!
