### ISSUE TITLE
Arrow.kt is broken...

### ISSUE THREAD

**Issue by xulman** [scenerygraphics/scenery#321]
... as a result of changes in Line.kt

**Comment by xulman** [comment]
(would not mind to have it assigned it to myself...)

**Comment by skalarproduktraum** [comment]
Could you be more specific? At least the unit tests are working.

**Comment by xulman** [comment]
when the `Line` changed some time back (was previously using some extra points) this class got no update and consequently it is not drawing vectors anymore... but rather some line mess

**Comment by xulman** [comment]
SORRY, I take back...
was about to fix it right now and noticed it works well, hmm
