### ISSUE TITLE
Consider changing blacklist to blocklist

### ISSUE THREAD

**Issue by ctrueden** [scenerygraphics/scenery#322]
See https://twitter.com/leahculver/status/1269109776983547904

**Comment by skalarproduktraum** [comment]
Yep, this is a good idea that I actually already wanted to implement, but did not have time yet. Thanks for bringing it up!

**Comment by xulman** [comment]
seriously??
it is profession terminology, far from any ethical interpretation....
sad to see how easily we are bending our backs just because somebody was bored....

**Comment by ctrueden** [comment]
@xulman It takes 2 minutes to change. We waste more time discussing than just doing it. What's the harm?

**Comment by skalarproduktraum** [comment]
Guys, stop discussing, it's already done in #326, I find blocklist to be the nicer term anyway.
