### ISSUE TITLE
Bug in rendering of floor (incorrect render ordering)

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/scenery#331]
In this scene all nodes are spheres with coordinates > 0 in all dimensions 

![floorbug](https://user-images.githubusercontent.com/400105/94158058-ecfb8700-fe4f-11ea-8a12-5e53bb1bf9de.gif)

**Comment by skalarproduktraum** [comment]
I can (un)fortunately not reproduce this, do you have some code for me so I can try?

**Comment by skalarproduktraum** [comment]
Fixed in dc40185 👍
