### ISSUE TITLE
Bounding grids for volumes are still broken

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/scenery#332]
The bounding box is technically there in some form:
![image](https://user-images.githubusercontent.com/400105/94161251-7cef0000-fe53-11ea-9fd5-978450eb7601.png)

But when the volume is visible, the bounding grid is not displayed

![image](https://user-images.githubusercontent.com/400105/94161175-6779d600-fe53-11ea-88c9-ec19e11e22fa.png)

**Comment by skalarproduktraum** [comment]
Fixed with 8ecb9746 and #336.
