### ISSUE TITLE
Language specific directories in test?

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/scenery#333]
Should there be language specific directories in the test directory to separate Kotlin and Java?

**Comment by skalarproduktraum** [comment]
I don't see a very good reason for it, apart from discoverability. Opinions?

**Comment by kephale** [comment]
Yeah, I don't feel strongly about this in scenery since almost everything is kotlin. I brought it up because there is more of a mix of java and kotlin in sciview so i am keeping them separated
