### ISSUE TITLE
"shaky" movements

### ISSUE THREAD

**Issue by xulman** [scenerygraphics/scenery#337]
Hi,
look here: https://www.fi.muni.cz/~xulman/files/backAndForthUpdates.avi

it's smooth mouse move right, then left (fps control), then shift+w, then shift+s.. kept holding it:
was expecting view to move normally, instead saw "shaky" move

this time all, hopefully, good on my side: linux, rebooted :-), fresh drivers, kernel, etc. openSuse distro,all updated

scenery: master ff66750b69ef6ae1a4cbb1b5f32ad4be9a227a2a with vlado'sFork/PC_camControls_addon_takeTwo rebased on it
sciview: master ca16a166795726d27a36b059248d3b86f3aec0d0 with PR_UXchanges_takeTwo rebased on top of it

**Comment by xulman** [comment]
15:09:51.732 [SciJava-f4943e0-Thread-0] ERROR loci.formats.ClassList - "loci.formats.in.BDVReader" is not valid.
15:09:51.828 [SciJava-f4943e0-Thread-1] INFO SciView - Started application as PID 8133
15:09:51.842 [SciJava-f4943e0-Thread-1] INFO SciView - imagej-launcher version bigger that non-working version (5.0.3 vs. 4.0.5), all good.
Resetting language to Python
15:09:55.322 [SciJava-f4943e0-Thread-1] INFO SciView - This is sciview / scenery ( / )
15:09:57.751 [SciJava-f4943e0-Thread-1] INFO VulkanRenderer - Loaded Deferred Shading (Deferred Shading, with HDR postprocessing and FXAA)
15:09:58.379 [SciJava-f4943e0-Thread-1] INFO VulkanDevice - Physical devices: 
15:09:58.384 [SciJava-f4943e0-Thread-1] INFO VulkanDevice -   0: Intel Intel(R) HD Graphics 530 (Skylake GT2) (IntegratedGPU, driver version 19.3.4, Vulkan API 1.1.102) (selected)
15:09:58.385 [SciJava-f4943e0-Thread-1] INFO VulkanDevice - Creating 1 distinct queue groups
15:09:58.416 [SciJava-f4943e0-Thread-1] INFO VulkanRenderer - Using swapchain SwingSwapchain
15:09:58.776 [SciJava-f4943e0-Thread-1] INFO VulkanRenderer - Renderer initialisation complete.
15:09:59.031 [SciJava-f4943e0-Thread-1] INFO InputHandler - No custom key configuration found, using default keybindings.
15:09:59.251 [SciJava-f4943e0-Thread-1] INFO VulkanRenderer - Recreating Swapchain at frame 0 (SwingSwapchain)
15:09:59.254 [SciJava-f4943e0-Thread-1] INFO SwingSwapchain - Selected present mode: VK_PRESENT_MODE_IMMEDIATE_KHR with 3 images
15:09:59.270 [SciJava-f4943e0-Thread-1] INFO VulkanRenderer - Creating render framebuffer GeometryBuffer for pass Scene (1244x667)
15:09:59.271 [SciJava-f4943e0-Thread-1] INFO VulkanRenderer -  + attachment NormalsMaterial, RGBA_Float16
15:09:59.274 [SciJava-f4943e0-Thread-1] INFO VulkanRenderer -  + attachment DiffuseAlbedo, RGBA_UInt8
15:09:59.274 [SciJava-f4943e0-Thread-1] INFO VulkanRenderer -  + attachment ZBuffer, Depth32
15:09:59.284 [SciJava-f4943e0-Thread-1] INFO VulkanRenderer - Creating render framebuffer AOTemp1 for pass AO (1244x667)
15:09:59.284 [SciJava-f4943e0-Thread-1] INFO VulkanRenderer -  + attachment Occlusion, R_UInt8
15:09:59.286 [SciJava-f4943e0-Thread-1] INFO VulkanRenderer - Creating render framebuffer AOTemp2 for pass AOBlurV (1244x667)
15:09:59.286 [SciJava-f4943e0-Thread-1] INFO VulkanRenderer -  + attachment Occlusion, R_UInt8
15:09:59.287 [SciJava-f4943e0-Thread-1] INFO VulkanRenderer - Creating render framebuffer AOBuffer for pass AOBlurH (622x333)
15:09:59.287 [SciJava-f4943e0-Thread-1] INFO VulkanRenderer -  + attachment Occlusion, R_UInt8
15:09:59.288 [SciJava-f4943e0-Thread-1] INFO VulkanRenderer - Creating render framebuffer ForwardBuffer for pass DeferredLighting (1244x667)
15:09:59.288 [SciJava-f4943e0-Thread-1] INFO VulkanRenderer -  + attachment Color, RGBA_Float16
15:09:59.290 [SciJava-f4943e0-Thread-1] INFO VulkanRenderer - Creating render framebuffer HDRBuffer for pass ForwardShading (1244x667)
15:09:59.290 [SciJava-f4943e0-Thread-1] INFO VulkanRenderer -  + attachment Color, RGBA_Float16
15:09:59.291 [SciJava-f4943e0-Thread-1] INFO VulkanRenderer -  + attachment Depth, Depth32
15:09:59.293 [SciJava-f4943e0-Thread-1] INFO VulkanRenderer - Creating render framebuffer FXAABuffer for pass HDR (1244x667)
15:09:59.293 [SciJava-f4943e0-Thread-1] INFO VulkanRenderer -  + attachment Color, RGBA_UInt8
15:09:59.912 [SciJava-f4943e0-Thread-1] INFO VulkanRenderer - Scene initialization started.
15:10:00.057 [SciJava-f4943e0-Thread-1] INFO VulkanRenderer - Scene initialization complete, took 14.478987 ms.

**Comment by xulman** [comment]
yes, confirmed, repeatedly pressing 'w' does really a couple of (expected) forward steps, then one backward
also, pressing 'd' moves right (and occasionally left), the no artitrary long delay, press 'w'... and see right move
delay can be very long... I got back to its window after wriing this comments, and it has shown me moves from before, and only then it reacted to what I pressed just now



it works well with -Dscenery.Renderer=OpenGLRenderer
(this was the only change in the env, the same code, same hw, etc

**Comment by xulman** [comment]
disabling push mode does not work

**Comment by skalarproduktraum** [comment]
Thank you for the report and the help with fixing it, @xulman! Bug is fixed with 7e5780a.
