### ISSUE TITLE
Slicing Volumes

### ISSUE THREAD

**Issue by moreApi** [scenerygraphics/scenery#373]
> As a user I want to be able to slice a volume to "look into it". I want be able to choose between simply not rendering the sliced part or displaying the 2d slice plane of the volume without transparency or volume rendering.

Results of the meeting of 11.02:

* Volume and Slicing Plane will be separate nodes
* Slicing will be done on a node by node basis and not globally in the `volumeManager`
* It will be possible to assign 1 to n relation between Slicing Planes and Volumes
* It will be possible to select which slicing mode to use
* The "cut away" mode is already implemented but only in `volumeManager` (same local plane for each volume)
* The "show 2d Slice" mode is likely easy doable with support from bigVolumeViewer
* Planned for the future is synchronization of the slicing plane with bigDataViewer

**Comment by moreApi** [comment]
Implementation-wise I would have a local slicing plane uniform for each volume and do all other calculation on the cpu, at least for the cut-away mode.

**Comment by moreApi** [comment]
![image](https://user-images.githubusercontent.com/10872331/107627376-7bd23a00-6c5f-11eb-83ef-7ff1160e0996.png)
(Example of cut-away slicing: an upside-down head with a sliced skull)

**Comment by moreApi** [comment]
Waiting on custom uniforms for volumes by @skalarproduktraum

**Comment by kephale** [comment]
Note that this issue is related: https://github.com/scenerygraphics/sciview/issues/2

**Comment by skalarproduktraum** [comment]
Done in #380 👍
