### ISSUE TITLE
All mouse buttons seem to be recognized as button1

### ISSUE THREAD

**Issue by moreApi** [scenerygraphics/scenery#377]
Move the camera works with all mouse buttons but should only be possible with button1. Also, commands wich are assigned to button 2 and 3 do not work.

In my initial investigation I found line 101 in `GLFWMouseAndKeyHandler` to be strange as the pressed button is always set to 0 same goes for the drag event above. However, this might not be relevant as the `getMask` method does not access that value. But that is also the point were I stopped my investigation as my knowledge of AWT input mask is lacking. Maybe the error is there somewhere. I don't see any code adding anything single button 2 and 3 clicks to the mask. And going with the debugger there and pressing left or right mouse buttons results in the same mask (1024).

Also scenerygraphics/sciview#356 of sciviewe might be related.

**Comment by moreApi** [comment]
still valid

**Comment by kephale** [comment]
bump

**Comment by moreApi** [comment]
scrolling also does not work under windows

**Comment by skalarproduktraum** [comment]
I should note here that on macOS, Swing is used instead of GLFW.
