### ISSUE TITLE
NullPointerException in RibbonDiagram

### ISSUE THREAD

**Issue by skalarproduktraum** [scenerygraphics/scenery#390]
This seems to happen not really deterministically, could you please have a look, @Domino2357? 
See e.g. the test log at https://github.com/scenerygraphics/scenery/runs/2193828815#step:6:127

**Comment by skalarproduktraum** [comment]
Another one, same line, log at https://ci.appveyor.com/project/skalarproduktraum/scenery/builds/38455773

**Comment by Domino2357** [comment]
See #392
