### ISSUE TITLE
Gradle doesn't propagate transitive dependencies to projects that depend on sciview

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/scenery#397]
When you try to depend on the gradle versions of scenery in sciview the transitive dependencies aren't inherited. 

This happened for:
- bigvoumeviewer
- lwjgl
- maybe more but I stopped checking at that point.

We definitely need to solve this for sciview, where maven projects will definitely try to depend on sciview.

@elect86

**Comment by elect86** [comment]
we can make them available to consumers

**Comment by kephale** [comment]
ok, can we sanity check that with scenery deps propagating to sciview (if you do a maven build of sciview)

**Comment by elect86** [comment]
Any tips about which are the next dependencies to propagate?

**Comment by skalarproduktraum** [comment]
This is already working now for Maven-based projects, and potentially fixed in #424 for Gradle-based projects (including sciview). Sciview itself might need the fix from #424 though, for jitpack-based builds.

**Comment by elect86** [comment]
How can we test?

**Comment by skalarproduktraum** [comment]
@elect86 this is fixed as of #424. The propagation of deps via Maven POMs was working already, but the incorrect Gradle .module file created by jitpack prevented this from working correctly for Gradle. If you wanna test it yourself, make a fresh sciview clone, and use scenery version `dabb0c5f` and see if everything works correctly.
