### ISSUE TITLE
Upgrade to non-snapshot dependencies

### ISSUE THREAD

**Issue by skalarproduktraum** [scenerygraphics/scenery#40]
Current offenders are:

* ~~LWJGL (currently at version 3.1.1-SNAPSHOT, 3.1.1 release should arrive in the week before Xmas)~~ moved to 3.1.1
* ~~spirvcrossj (currently at version 0.1-SNAPSHOT, release in preparation)~~ moved to 0.2.4 with e63e3dfa5d8bd7c2591b5571799cb2b0f30dc17a
* ~~script-editor (at 0.1.1-SNAPSHOT)~~ moved to 0.1.1
* ~~scripting-javascript (at 0.4.4-SNAPSHOT)~~ moved to 0.4.3
* ~~ClearGL (currently at 2.0.0-SNAPSHOT, release in preparation)~~ moved to 2.0.1

**Comment by skalarproduktraum** [comment]
@ctrueden is there a chance to get script-editor and scripting-javascript bumped to the next stable?

**Comment by ctrueden** [comment]
@skalarproduktraum How soon do you need them? I will be cutting a ton of releases some time "soon" but I could do a release cycle for your urgently needed components tomorrow if you really need it now.

**Comment by skalarproduktraum** [comment]
@ctrueden Thanks for the quick and (as usual, detailed 👍 ) response! I'll check that out tomorrow, I thought you had fixed something there which I needed, but it could be that this was moved to ui-swing (at least I remember something along these lines). I'll let you know of the results then.

**Comment by skalarproduktraum** [comment]
scijava and lwjgl dependencies have been bumped to non-snapshot versions with 98867ac3466d92e3fea0079b5f0569c878f37a3e, spirvcrossj and ClearGL are pending.

**Comment by skalarproduktraum** [comment]
Only spirvcrossj remaining now.

**Comment by skalarproduktraum** [comment]
spirvcrossj moved to 0.2.4 with e63e3dfa5d8bd7c2591b5571799cb2b0f30dc17a, closing the issue.
