### ISSUE TITLE
Support for "legacy" systems? (e.g. GLIBCXX_3.4.19-)

### ISSUE THREAD

**Issue by DrDaleks** [scenerygraphics/scenery#451]
Hi,
I'm currently trying to deploy a scenery-based app on some target environment that is stuck at RHEL7 (meaning, among other things, gcc 4.8.5 / libstdc++ 6.0.19, no upgrade possible). This means I currently can't deploy my app on said system, as it requires at least GLIBCXX_3.4.20 to load the native libraries.

So before I attempt anything fiddly, I'll throw out the question here first: would it be possible to build the bindings with an earlier version of gcc (according to sprivcrossj's README, the gcc and cmake are ok, but swig is 2.0.10 < 3.0).

If not, I guess it'd be nice to mention this somewhere on scenery's own README in the form of minimal system requirements, just to clarify things to the end(-ish) user.
Cheers

**Comment by skalarproduktraum** [comment]
Hey @DrDaleks! I apologise for the late reply!  

With regard to older system, that might be difficult. The native libraries we use mostly come from other projects, such as [lwjgl](https://github.com/lwjgl/lwjgl3), so we have limited influence over the dependencies, or glibc version used. RHEL7 might pose other challenges as well, I have no idea whether a halfway up-to-date Vulkan runtime is available for this (sorry) rather ancient distribution. Maybe you can join our developer chat at gitter.com/scenerygraphics/SciView, so we can discuss a bit more and maybe figure something out?

cheers!

**Comment by skalarproduktraum** [comment]
As there has been no further reply, I am closing this. @DrDaleks, feel free to reopen if you have further questions 👍
