### ISSUE TITLE
A function that can read XML/h5 files as RAIVolume is needed 

### ISSUE THREAD

**Issue by RuoshanLan** [scenerygraphics/scenery#481]
I have many XML/h5 files that should be recognized as RAIVolume. But now they can only be read as Volume(https://github.com/scenerygraphics/scenery/blob/master/src/main/kotlin/graphics/scenery/volumes/Volume.kt#L388-L424). I need this function for RAIVolumeSamplingExample.

**Comment by skalarproduktraum** [comment]
This is being addressed in #482
