### ISSUE TITLE
Wrong resolution levels loaded for BDV XML/N5 datasets

### ISSUE THREAD

**Issue by skalarproduktraum** [scenerygraphics/scenery#493]
There is currently an issue in volume rendering, when rendering multiresolution BDV XML/N5 datasets. It looks like too-low resolution levels are loaded:

![BDV Rendering example - 2022-10-26 11 43 25](https://user-images.githubusercontent.com/586495/197993908-e079513b-be67-457f-bd7f-61c2c83afaf5.png)

I have added a workaround that constrains the resolution levels to a given interval, e.g. when constraining to [0, 1], the result is the following (which is what the first image would actually be supposed to look like):
![BDV Rendering example - 2022-10-26 11 44 58](https://user-images.githubusercontent.com/586495/197994043-816f6017-4dd1-48c1-b627-4189ca92e954.png)

My investigation so far has yielded the following points:
* The issue is 100% reproducible (tested on macOS and Windows)
* `git bisect` shows the behaviour broke between 6f12585b39fb3b7fb7bbaaf65acc4b3898703826 (still good) and 1fd80eeb2e9be0ed082cb2483656f07fd51263e9 (broken). This is where the change from GLVector/GLMatrix to JOML was made.
* Renderdoc yielded that projection, view and model matrices seem to be set correctly, both with `MultiVolumeShaderMip.setProjectionMatrix()` and with `VolumeBlocks.init()`
* Renderdoc also yielded that in the broken case, the LUT texture is much smaller than in the working case, while uniforms look reasonable in both cases. When debugging into `MipmapSizes.init()`, which is called by `VolumeBlocks.init()` it looks as if the values of `sn` and `sf` are off, while the rest looks okay. This then leads to the wrong resolution levels being determined (3 in the broken case, 0 and 1 in the working case).
* ~~Changing the near and far plane of the projection matrix changes the resolution levels loaded.~~ Behaviour is actually correct, my interpretation was not, though.
* volume cache updates and LUT updates are correctly processed and loaded onto the GPU

**Comment by tpietzsch** [comment]
> * This is where the change from GLVector/GLMatrix to JOML was made.

Did this perhaps change the JOML version? (from the transitive JOML dependency of bvv to explicit dependency)

**Comment by skalarproduktraum** [comment]
Sorry, this is another point I should have added above:
* checked different JOML versions, up from the one used in BVV in the working commit, to the current one used in scenery

**Comment by skalarproduktraum** [comment]
I just had a look again at JOML's changelogs. There has been a bugfix in `Vector4.mulProject` in 1.9.18 that looks suspicious. The broken version uses 1.9.22, while the working one uses 1.9.12. I'll double-check this tomorrow.

**Comment by skalarproduktraum** [comment]
Okay, I actually couldn't hold back now. Aaaaaand - reverting back to 1.9.12 works! I had actually made a mistake in forcing the JOML version in the Gradle build file, and now did it the right way. We should nevertheless have a chat tomorrow to see how this can be fixed. I bet the JOML bugfix I mentioned above is the culprit here.

**Comment by skalarproduktraum** [comment]
Watches for `MipmapSizes.init` with JOML 1.9.12:
<img width="538" alt="mipmap-1 9 12-moredata" src="https://user-images.githubusercontent.com/586495/198547366-867aebfa-b72d-45b5-a8dc-9c6abc42a9ae.png">

Watches for `MipmapSizes.init` with JOML 1.10.4:
<img width="516" alt="mipmap-1 10 4-moredata" src="https://user-images.githubusercontent.com/586495/198547374-4e3e68d5-8c25-4dc4-b7d7-efe8b384a9b1.png">

* MVP, `sn` and `sf` are the same
* pFar and pNearToFar are different, likely an issue with `unprojectInvRay`

**Comment by skalarproduktraum** [comment]
Thanks to a nice Heisenbug hunting session with @tpietzsch, the culprits turned out to be the use of `Matrix4f.unprojectInvRay()` in combination with `MipmapSizes.init()`. The latter contains the assumption that the ray returned from `unprojectInvRay()` reaches from the near to the far plane. This was the case until JOML 1.9.17. In JOML 1.9.18, this changed, due to the support for far plane at infinity. This effectively removes a `far/near` division from the ray length, leading to a ray that doesn't touch the far plane.

In scenery, there are order-of-magnitude differences between near and far plane, while in BVV, they are of the same order. The issue did therefore not appear in BVV. As `Matrix4f.unprojectInvRay()` never promised to actually return a ray that reaches the far plane, we will handle this internally, either by using the old implementation of `unprojectInvRay()`, or by scaling the resulting ray correctly.
