### ISSUE TITLE
Shift key does not register in input handler

### ISSUE THREAD

**Issue by smlpt** [scenerygraphics/scenery#566]
GLFW does register shift key events, but they won't reach the behavior. E.g. fast movement with Shift + WASD is not possible; the movement simply stops after the first small step.

Maybe this is related to the changes @skalarproduktraum made last week in commit 845224e?

**Comment by moreApi** [comment]
I am trying out git besect to see where it breaks

**Comment by moreApi** [comment]
well, no need for that. You were correct @smlpt. It is https://github.com/scenerygraphics/scenery/commit/845224e4d63d5a855f61fbcded3804d206f5bb65 at fault.

**Comment by moreApi** [comment]
alt and ctrl also break the input

**Comment by moreApi** [comment]
the key code for modifies are wrong. it should be somthing like 16-18 and it is 340-342

**Comment by moreApi** [comment]
https://www.glfw.org/docs/3.3/group__keys.html this is the corresnpoding key code list. 340-342 is for the left modifiers
