### ISSUE TITLE
Enable VR for scenery

### ISSUE THREAD

**Issue by krzysg** [scenerygraphics/scenery#60]
In current master branch change true -> false in VulkanRenderer.kt and possibly OpenGLRenderer.kt in line:
ds.set("vr.Active", false)

However, in latter one it seems to be some problem - OpenGL renderer starts and allows to play with it a few seconds and then app crashes (in my case SponzaExample.kt  test) or it still works on PC screen but not anymore on VR headset.

**Comment by skalarproduktraum** [comment]
Yes, this setting should definitely be handled more transparently, or removed in total.

The last part however, I don't really get: So if you run it with `vr.Active=true`, it runs for a bit on your DK1, but then crashes on the headset, and continues to run on the PC monitor? Did I understand this correctly?
