### ISSUE TITLE
Convenience functions in HasGeometry for vertices and indices

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/scenery#63]
There are now 2 Scenery-based projects where I need to get vertices and indices as float/int arrays. Might as well store that logic in HasGeometry

**Comment by skalarproduktraum** [comment]
Could you elaborate? Is this issue still relevant?

**Comment by skalarproduktraum** [comment]
Poke @kephale

**Comment by skalarproduktraum** [comment]
Poke 2.0 @kephale

**Comment by kephale** [comment]
Sorry for the delay. I think this is probably irrelevant for my use cases because of imagej-mesh.
