### ISSUE TITLE
Screenshot functions in renderers should return data not write to file

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/scenery#67]
We need to get the image data into structures that we can immediately load into ImageJ (that is how the current implementation of screenshot in ThreeDViewer works as well; by making BuffereImages that get converted to ImagePlus's).

**Comment by kephale** [comment]
Alright. I just checked out the status of screenshots again and all of the good stuff is there, but it would be worth rearranging things. 

My current thought is to make 2 modifications:
1. add a ScreenshotBufferedImage() function [whatever the name is] that stores the screenshot BufferedImage into a temporary variable in the renderer
2. use the current filenaming scheme as the default behavior, but allow the filename to be customized

IMHO (1) is much more important than (2)

**Comment by kephale** [comment]
What about doing this by either allowing a callback function as input, or returning the buffer as a future?

**Comment by kephale** [comment]
Screenshots

**Comment by skalarproduktraum** [comment]
This needs to be async however. I'll see that I can implement this with returning a Future, containing the a buffer and it's metadata.

**Comment by skalarproduktraum** [comment]
Implemented in 69c5749 👍
