### ISSUE TITLE
Resizing transfer function/colormap editor changes rendering of volume

### ISSUE THREAD

**Issue by moreApi** [scenerygraphics/scenery#698]
**Describe the bug**
[link to jans nextcloud with example video](https://cloud.viings.de/index.php/s/nYrtYKQCAQCrsDR )

**To Reproduce**
1. have a volume (eg procedual generated volume example)
2. open tf/colormap editor for it
3. resize editor window
4. enjoy color show

**Expected behavior**
Resizing of editor window does not cahnge rendering of volume

**Comment by moreApi** [comment]
Introduced in #688

**Comment by skalarproduktraum** [comment]
This is fixed in #701
