### ISSUE TITLE
Instancing for PointClouds

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/scenery#82]
Use instancing for PointCloud to reduce shader burden.

**Comment by skalarproduktraum** [comment]
What would you like to instance there? Simply using points as a primitive is guaranteed to be faster than any kind of instancing. Could you please clarify? :)

**Comment by kephale** [comment]
Hey, it was past Ulrik's suggestion! That said, I think this had to do with the way quads being generated on the fly when rendering points, but perhaps is not an issue with large point (1-10M points were my test case) clouds.

**Comment by skalarproduktraum** [comment]
Okay, so this is actually fixed then with #101, I'll close this for the moment. In case trouble reappears, please reopen 👍
