### ISSUE TITLE
Mesh gets upside down when the window is resized (using JavaFX)

### ISSUE THREAD

**Issue by ssinhaleite** [scenerygraphics/scenery#90]
I'm running this [example](https://github.com/ssinhaleite/MarchingCubes/blob/master/src/tests/JavaFXApplication.java) and when the window is resized, the mesh turns upside down.

**Comment by skalarproduktraum** [comment]
I'll close this, as it's fixed with ae3dc6bd621a8dba05e62c554364781e28ec66dd. Please feel free to reopen, should the problem persist :)
