### ISSUE TITLE
JavaFX scene without controls

### ISSUE THREAD

**Issue by ssinhaleite** [scenerygraphics/scenery#91]
I created an small [JavaFX application](https://github.com/ssinhaleite/MarchingCubes/blob/master/src/tests/ExampleApplication.java) using scenery, and it is almost working: I can see the scene, but I cannot move the camera at all. Have you observed something like this before?

**Comment by ssinhaleite** [comment]
Hey, I was checking here this issue and I realize that I need to create an InputHandler (using the SceneryDefaultApplication the InputHandler comes for free). The catch now is: after creating the InputHandler the mouse started to work beautifully, but the keys don't. In fact, some keys are working (for instance, Q, O, H and P) but not the keys that control the camera (W, A, S, D). This can be checked in this example: [javaFXApplication](https://github.com/ssinhaleite/MarchingCubes/blob/master/src/javafx/JavaFXApplication.java) and [scenery scene](https://github.com/ssinhaleite/MarchingCubes/blob/master/src/javafx/SimpleSceneryScene.java)

**Comment by skalarproduktraum** [comment]
Hi @ssinhaleite,

your custom application code does not use SceneryDefaultApplication and is lacking a subtle, but crucial line: https://github.com/scenerygraphics/scenery/blob/72c71115d39f64d32b2b36b1b8159f1df0e1a563/src/main/kotlin/graphics/scenery/SceneryDefaultApplication.kt#L175

This line is there so you get constant camera movement speeds, even if the framerate varies. You need to update this in your application code, or set it to a constant -- but then you'll get non-constant movement speeds, which might be unintuitive. I'd suggest you use SceneryDefaultApplication. Was there a reason not to use it?

**Comment by ssinhaleite** [comment]
Hey, @skalarproduktraum!

Thank you for your reply! I tried to use the SceneryDefaultApplication together with my JavaFX application but without success. When I am using the JavaFX application, and I call a Scenery application, a window appears, but without any render. 
[Here](https://github.com/ssinhaleite/MarchingCubes/blob/master/src/javafx/JavaFXApplicationSceneryApplication.java) is a small example with a JavaFX application that calls the [Scenery application](https://github.com/ssinhaleite/MarchingCubes/blob/master/src/javafx/SimpleSceneryApplication.java). I am using a JavaFX application since the scenery will be only one part of my application. I will really appreciate any insights in how to solve this. Thanks a lot!

**Comment by skalarproduktraum** [comment]
Hi @ssinhaleite,

if you run SceneryDefaultApplication::main in the JavaFX's Application::start method, it'll block forever. The solution is to run it in a separate Thread, like `new Thread(() -> {sceneryApplication.main();}).start();`

I hope this helps!

**Comment by skalarproduktraum** [comment]
Oh, and additionally, the panel where you'd want to embed Scenery in should be a parameter to SimpleSceneryApplication and _not_ be set afterwards, because by that time the renderer will already have been constructed and will not know about the panel.

**Comment by ssinhaleite** [comment]
Hey, @skalarproduktraum,

Thank you again for your prompt reply! Indeed this is what I was missing! Now I have the controls using the SceneryDefaultApplication! :+1:

**Comment by skalarproduktraum** [comment]
Hey @ssinhaleite,

I'm glad to hear that! With the next release, I'll also make things a bit clearer:
* SceneryDefaultApplication has been renamed SceneryBase, as it actually does not contain any windowing system-specific code and should actually be used as a base in general
* it'll also spit out a warning in case it is run in the JavaFX Event Thread, because it'll then continue to block it, as you have experienced (`Application::start()` is assumed to return asap by JavaFX).

I'd close the issue for now, if there are further problems along these lines, please reopen the issue :)

cheers!
