### ISSUE TITLE
Seeking collaboration

### ISSUE THREAD

**Issue by elect86** [scenerygraphics/scenery#98]
Hi, 

sorry if I open this here, this is not really an issue, but rather a proposal

I just ended randomly on your `OpenGLRenderer.kt` because I was thinking to implement an iterator for buffers...

This project looks amazing. Honestly in the past I had a raw idea to do something like this (vr scientific visualitation tool) for a friend working in EMBL here in Hamburg, but I never had the chance given the times and prorioties.

But what I do have is a collection of tools, we are developing, explicitely designed for graphics in kotlin

https://github.com/kotlin-graphics/

My final intentions are essentially to fine and tune that tools and I guess/hope we can both benefit from a synergy/collaborations

What do you think, guys? :)

Ps: https://scenery.graphics is broken

**Comment by skalarproduktraum** [comment]
Hey Giuseppe!

That sounds pretty good :-) Cool work the kotlin-unsigned project btw, I'll use that soon :-D

Maybe you want to drop by at our gitter channel at https://gitter.im/scenerygraphics? We could discuss a bit more there -- I guess the room is a little better suited to interactive discussions than the issue system 👍 

Oh, and also thanks for reminding me that the https version of scenery.graphics is broken... it's at the moment only an el-cheapo http redirect, which I'll need to fix... >_<

cheers!
